spring.application.name=smart-finance-manager-backend

# Set the server port
server.port=9090

# Database Configuration (MySQL Example)
spring.datasource.url=jdbc:mysql://localhost:3306/smart_finance_db
spring.datasource.username=root
spring.datasource.password=thesahoo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
